#!/bin/sh

AOCL_BOARD_PACKAGE_ROOT="/opt/altera_pro/16.0/hld/board/altera_a10socdk/"
TARGET=$1
BOARD_PACKAGE_NAME=a10soc_2ddr
SUFFIX=$1

echo "aoc --save-temps --profile -v -g ./device/${TARGET}.cl -o ./to_a10soc/${TARGET}.aocx --board ${BOARD_PACKAGE_NAME} --report"
aoc --save-temps --profile -v -g ./device/${TARGET}.cl -o ./to_a10soc/${TARGET}.aocx --board ${BOARD_PACKAGE_NAME} --report
